### ISSUE TITLE
The node server dashboard should provide a control to update the node server's profile files on the ISY

### ISSUE THREAD

**Issue by bpaauwe** [UniversalDevicesInc/pg3#10]
The Polyglot node server dashboard should be the location used for controlling the node server. This includes providing a control that asks the node server to send its profile files to the ISY.

**Comment by jimboca** [comment]
The nodeserver should handle updating it's profile on it's own as needed, there is already that functionality to automatically handle that in PG2 local by setting profile_version in the server.json.

**Comment by bpaauwe** [comment]
Implemented in 3.0.15 release
