### ISSUE TITLE
Polyglot should be able to notify the ISY with the status of each node server

### ISSUE THREAD

**Issue by bpaauwe** [UniversalDevicesInc/pg3#13]
This probably requires a new rest endpoint in the ISY firmware that accepts the status of the node server.

The goal is to allow the ISY to report the status of all installed node servers and use that status as a trigger in programs.

**Comment by jimboca** [comment]
How is this different then ST on the Controller, that's what it's for?

**Comment by bpaauwe** [comment]
> How is this different then ST on the Controller, that's what it's for?

I don't want to waste node resources showing the status of node servers.  Node servers are becoming an integral part of the ISY and as such should be better integrated.  

The nodes created by node servers should be for control/status of the devices managed by the node server, not the node server itself.  The creation and use of a "control" node isn't a good design (It's all we have for PG2 though) and PG3 gives us the chance to fix the design and make it better.

**Comment by jimboca** [comment]
Ok, that's a huge change on the ISY side, so way beyond PG3's timeline, IMO...

**Comment by bpaauwe** [comment]
Based on @mkohanim comments elsewhere, they're looking at adding things like support for strings in the ISY firmware so this is minor compared to that.    Since I haven't seen what PG3 actually looks like yet, I figured I might as well start asking for everything and maybe some of it will make it.

**Comment by mkohanim** [comment]
As far as I remember, the addition of the controller node and its status was so that the customers could figure out whether or not the node server is alive/responding. Not really sure I understand what’s being proposed here.

With kind regards,

******************************
  Michel Kohanim
  CEO

  (p) 818.631.0333
  http://www.universal-devices.com<http://www.universal-devices.com/>
******************************

**Comment by jimboca** [comment]
> Based on @mkohanim comments elsewhere, they're looking at adding things like support for strings in the ISY firmware so this is minor compared to that. Since I haven't seen what PG3 actually looks like yet, I figured I might as well start asking for everything and maybe some of it will make it.

Yes, just saying that's beyond the scope and timeline @mkohanim had discussed for PG3, and I would say it's very major change to how nodeservers work, not just for polyglot.

**Comment by bpaauwe** [comment]
> As far as I remember, the addition of the controller node and its status was so that the customers could figure out whether or not the node server is alive/responding. Not really sure I understand what’s being proposed here. With kind regards, ****************************** Michel Kohanim CEO (p) 818.631.0333 http://www.universal-devices.com<http://www.universal-devices.com/> ****************************** 

I agree that customers need to know if a node server is alive/responding. I'm suggesting that there is a better way to do that, but that it requires a change in the both Polyglot and the ISY firmware to implement.

The ISY firmware simply needs to have a new REST endpoint, say something like /rest/ns/<profile num>/status?online|offline|crashed

The ISY can take then use this as a program trigger condition (status/node server/<name> = or != (list: online, offline, crashed) and it could also display this from the admin console via  a node server menu item (Node Servers -> Status pops up a window with the status of each installed node server).   

The ISY could also timestamp when it receives the status and and report a timeout or unresponsive status if it hasn't heard from Polyglot in x seconds/minutes.

I realize this is a pretty big change, but if PG3 is really going to be an improvement, now is the time to consider changes like this.

Note that this (and my other proposed changes) don't prevent node server authors from creating a control node and doing things the same way as they are being done now, it just make the control node optional/redundant for node servers written specifically for PG3.

**Comment by mkohanim** [comment]
@bob,

What makes your approach better? For a node server with 10 nodes, how would you represent the status of the node server with your new rest end point?

With kind regards,

******************************
  Michel Kohanim
  CEO

  (p) 818.631.0333
  http://www.universal-devices.com<http://www.universal-devices.com/>
******************************

**Comment by bpaauwe** [comment]
> @bob, What makes your approach better? For a node server with 10 nodes, how would you represent the status of the node server with your new rest end point? With kind regards, ****************************** Michel Kohanim CEO (p) 818.631.0333 http://www.universal-devices.com<http://www.universal-devices.com/> ****************************** 

I don't understand what the number of nodes created by the node server has to do with this. 

Correct me if I'm wrong, but aren't nodes on the ISY a representation of device status/control?   If so, then overloading a node to do node server status/control, while possible, seems wrong.  You're making the user use two different interfaces to interact with the node server (the Admin Console and Polyglot web interface).  

What is the requirement to represent the status of a node server?  My understanding is that the primary requirement is to allow the ISY to notify the user if that status changes.  Thus having node server status be something that is specifically tracked in the ISY and set via a new REST endpoint allows it to be used as a program trigger condition that can trigger that user notification.

It it is also a requirement that it be visible from the Admin Console, then you already have a "Node Server" menu item that shows some info about the installed node servers so why not add the status there.  My suggestion would be to add another submenu option for status like there is for config and have it open a window that shows the status of all installed node servers.  That would be more convenient than searching the node tree for a specific node server node to get the status.

**Comment by mkohanim** [comment]
@bob,

Obviously, I would love to understand what you are suggesting alas, at this juncture, I am not so sure how status of the node server itself can be used in programs. In ISY Programs, except for system defined things, everything is a node. Including the node server itself. So, how do you propose we represent the status of a node server itself in Programs? Is it something other than a node that also has the same features as a node (i.e. properties, events, NLS, commands, etc.)? If not, what is it?


With kind regards,

******************************
  Michel Kohanim
  CEO

  (p) 818.631.0333
  http://www.universal-devices.com<http://www.universal-devices.com/>
******************************

**Comment by bpaauwe** [comment]
> @bob, Obviously, I would love to understand what you are suggesting alas, at this juncture, I am not so sure how status of the node server itself can be used in programs. In ISY Programs, except for system defined things, everything is a node. Including the node server itself. So, how do you propose we represent the status of a node server itself in Programs? Is it something other than a node that also has the same features as a node (i.e. properties, events, NLS, commands, etc.)? If not, what is it? 

Really?  When I do "Node Servers->Configure->[05] node server" in the Admin Console I get a window that is populated with things like "Base URL", "Host Name", "Port", etc.  is that stored in a node somewhere?  It's not in any user visible node.   When I select "Node Servers->node server" I get the option to add a node or add all nodes.  That's not represented in any user visible node.

Why couldn't the node server's status be stored along with the other node server info and displayed to the user when they select "Node Servers->Status" or "Node Servers->node server->Status" from the menu?

Why can't an installed node server's status be a system defined thing?

**Comment by bpaauwe** [comment]
Ok, ignore this.  @mkohanim has convinced me that adding node server status to the ISY node server REST interface is not fitting with the long term goals for the ISY software.

**Comment by bob** [comment]
Hey @mkohanim, why you did mention me?

**Comment by mkohanim** [comment]
@bob, terribly sorry. It was a mistake.

With kind regards,

******************************
  Michel Kohanim
  CEO

  (p) 818.631.0333
  http://www.universal-devices.com<http://www.universal-devices.com/>
******************************
