### ISSUE TITLE
Add required custom configuration parameters in server.json

### ISSUE THREAD

**Issue by Goose66** [UniversalDevicesInc/pg3#18]
If nodeserver developers could add the required custom configuration parameters in server.json (along with default or example values), then the Polyglot Dashboard could, on install, provide the opportunity for users to set these parameters before first run, instead of having to run the nodeserver once, have it fail, providing notices to users to set the parameter values, and then having to restart the nodeserver.

**Comment by mkohanim** [comment]
I totally agree … we get so very much support calls with: it’s not working; it’s not populating … and, it’s all about the configuration parameters.

With kind regards,

******************************
  Michel Kohanim
  CEO

  (p) 818.631.0333
  http://www.universal-devices.com<http://www.universal-devices.com/>
******************************

**Comment by bpaauwe** [comment]
It is possible now, to write a node server that waits for the configuration parameters to be set and then does all it's startup functions so the user doesn't have to manually restart the node server.  I've tried to make most of mine behave this way now.  It's a pain to code as the OnConfig callback always just sends the current state of the configuration parameters so you have to keep track of what's changed. 

But I like the idea of using the server.json to do this.   For reference, here's an example of what I use 

`self.params = node_funcs.NSParameters([{
            'name': 'ClientID',
            'default': 'set me',
            'isRequired': True,
            'notice': 'AERIS Client ID must be set',
            },
            {
            'name': 'ClientSecret',
            'default': 'set me',
            'isRequired': True,
            'notice': 'AERIS Client Secret must be set',
            },
            {
            'name': 'Location',
            'default': 'set me',
            'isRequired': True,
            'notice': 'AERIS location must be set',
            },
            {
             'name': 'Units',
            'default': 'imperial',
            'isRequired': False,
            'notice': '',
            }])
`
Internally in my NSParameters class, I also track the current value so that I know if it has been changed.   I'm able to tell if all the required parameters have been set and then take appropriate actions in the node server (discovery, etc.).

**Comment by mkohanim** [comment]
I love it.

With kind regards,

******************************
  Michel Kohanim
  CEO

  (p) 818.631.0333
  http://www.universal-devices.com<http://www.universal-devices.com/>
******************************

**Comment by Goose66** [comment]
Ok, I am +1'ing my own post. It seems that writing a quick wizard to walk the user through the required and optional configuration parameters would be trivial and could be executed as soon as the Git clone command was finished (sucessfully) on install. 

Additionally, if an update of a nodeserver occurs, Polyglot could detect missing required parameters (that may be new) and add a notification to the Dashboard for the nodeserver while preventing the nodeserver from restarting. No use having it out there spinning and spinning when nothing useful can occur until the new configuration parameter is set.

**Comment by mkohanim** [comment]
+1

With kind regards,

******************************
  Michel Kohanim
  CEO

  (p) 818.631.0333
  http://www.universal-devices.com<http://www.universal-devices.com/>
******************************

**Comment by bpaauwe** [comment]
@Goose66 I started looking at adding customparams to the server.json file and have something basic working. If I add 
```
"customparams": {
	    "IP Address": "Enter ISY ip address here",
	    "Username": "Enter ISY username here",
	    "Password": "Enter ISY password here",
	    "New Parameter": "This is never used"
    },
```
to my server.json, I get this when installing the node server.
![results](http://www.bobshome.net/udi/pg3_backup_cfg.png)

This is a really small code change and I believe the same change can be made to support custom typed parameters as well.  This still means the node server has to deal properly with detecting changes, required and default values.

I'd like to see custom parameters have more attributes than just a key / value, but that's a much larger code change.

The code changes for this are in the branch topic/default-customparams

**Comment by bpaauwe** [comment]
Setting initial values for custom parameters in server.json file has been implemented.
