### ISSUE TITLE
version 3.0.13 - store not enforcing link to my.isy.io account

### ISSUE THREAD

**Issue by bpaauwe** [UniversalDevicesInc/pg3#22]
On initial install of PG3, going to the node server store the message says that node servers can't be installed until it is linked with the portal.  However, the "install" button is active for all node servers and I was able to install a node server without linking to my my.isy.io account.

**Comment by Einstein42** [comment]
You are only required to login and authenticate for non-free nodeservers. EG PythonTemplate.

**Comment by bpaauwe** [comment]
Then the wording should be changed to indicate that you must authenticate to purchase node servers.

**Comment by bpaauwe** [comment]
working as intended
