### ISSUE TITLE
version 3.0.13 - node server fails to start

### ISSUE THREAD

**Issue by bpaauwe** [UniversalDevicesInc/pg3#23]
After installing a node server, it fails to start with the error:

startNs: TypeError: Cannot read property 'stdin' of undefined
    at Object.startNs (/usr/home/bpaauwe/pg3/core/lib/services/nodeservers.js:376:43)

**Comment by Einstein42** [comment]
You need to use the pg3 python interface for pg3. https://github.com/UniversalDevicesInc/pg3-python-interface

**Comment by bpaauwe** [comment]
So how is this going to work?  I can't go modify existing node servers to use the new interface as that will break everyone else.  The PG3 store shouldn't be showing me node servers that aren't compatible with PG3.

**Comment by mkohanim** [comment]
Perhaps we should have a different repository for PG3?

With kind regards,

******************************
  Michel Kohanim
  CEO

  (p) 818.631.0333
  http://www.universal-devices.com<http://www.universal-devices.com/>
******************************

**Comment by bpaauwe** [comment]
A new node server store has been created and node server written for PG3 will need to be added to the store before they can be installed.
