### ISSUE TITLE
Creating a working branch breaks PG3

### ISSUE THREAD

**Issue by bpaauwe** [UniversalDevicesInc/pg3#25]
My normal git workflow when working on a node server is to work on a separate git branch. I created a new branch to hold the changes I was making to get the node server working on PG3 and got this error when trying to start the node server:

11/25/2020, 5:23:07 PM [pg3] info: [Backup(25)] :: Checking for update...
11/25/2020, 5:23:07 PM [pg3] error: startNs: Error: warning: Pulling without specifying how to reconcile divergent branches is
discouraged. You can squelch this message by running one of the following
commands sometime before your next pull:

  git config pull.rebase false  # merge (the default strategy)
  git config pull.rebase true   # rebase
  git config pull.ff only       # fast-forward only

You can replace "git config" with "git config --global" to set a default
preference for all repositories. You can also pass --rebase, --no-rebase,
or --ff-only on the command line to override the configured default per
invocation.

There is no tracking information for the current branch.
Please specify which branch you want to merge with.
See git-pull(1) for details.

    git pull <remote> <branch>

If you wish to set tracking information for this branch you can do so with:

    git branch --set-upstream-to=<remote>/<branch> pg3_testing

    at GitExecutorChain.onFatalException (/usr/home/bpaauwe/pg3/core/node_modules/simple-git/src/lib/runners/git-executor-chain.js:60:87)
    at GitExecutorChain.<anonymous> (/usr/home/bpaauwe/pg3/core/node_modules/simple-git/src/lib/runners/git-executor-chain.js:51:28)
    at Generator.throw (<anonymous>)
    at rejected (/usr/home/bpaauwe/pg3/core/node_modules/simple-git/src/lib/runners/git-executor-chain.js:6:65)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
11/25/2020, 5:23:07 PM [pg3] debug: MQTT Results: [frontend/ns/admin] :: {"startNs":{"success":false,"error":"warning: Pulling without specifying how to reconcile divergent branches is\ndiscouraged. You can squelch this message by running one of the following\ncommands sometime before your next pull:\n\n  git config pull.rebase false  # merge (the default strategy)\n  git config pull.rebase true   # rebase\n  git config pull.ff only       # fast-forward only\n\nYou can replace \"git config\" with \"git config --global\" to set a default\npreference for all repositories. You can also pass --rebase, --no-rebase,\nor --ff-only on the command line to override the configured default per\ninvocation.\n\nThere is no tracking information for the current branch.\nPlease specify which branch you want to merge with.\nSee git-pull(1) for details.\n\n    git pull <remote> <branch>\n\nIf you wish to set tracking information for this branch you can do so with:\n\n    git branch --set-upstream-to=<remote>/<branch> pg3_testing\n\n"}}

**Comment by bpaauwe** [comment]
After the above error I can no longer start the node server because it things it's already running.   Trying a restart results in:

11/25/2020, 5:37:28 PM [pg3] info: [Backup(25)]: Restarting Nodeserver
11/25/2020, 5:37:28 PM [pg3] info: [Backup(25)]: Stopping Nodeserver
11/25/2020, 5:37:31 PM [pg3] info: Backup stopped
11/25/2020, 5:37:34 PM [pg3] error: [Backup(25)] :: already running.
11/25/2020, 5:37:34 PM [pg3] debug: MQTT Results: [frontend/ns/admin] :: {"restartNs":{"success":false,"error":"already running"}}

so PG3 is now in some state that looks like it will require me to delete and re-install the node server.

**Comment by mkohanim** [comment]
Not good at all. So, basically, node servers cannot handle git branches?

With kind regards,

******************************
  Michel Kohanim
  CEO

  (p) 818.631.0333
  http://www.universal-devices.com<http://www.universal-devices.com/>
******************************

**Comment by bpaauwe** [comment]
I see some code in PG3 that looks incomplete, but maybe intended to allow it to use a different branch other than 'master'.  

However, this is mostly a problem when doing development and shouldn't be a problem for normal users.  I'm trying to document the issues I have as I try to port a NS to PG3.

**Comment by mkohanim** [comment]
Thank you Bob.

With kind regards,

******************************
  Michel Kohanim
  CEO

  (p) 818.631.0333
  http://www.universal-devices.com<http://www.universal-devices.com/>
******************************

**Comment by bpaauwe** [comment]
A simple solution is to add the --rebase option to the git pull that is being done to update the repository.  With that added, it will pull the most current version from the master branch but will then rebase the local changes on top.   This seems to work in the case where local changes have been added to the local master branch or when working on a local branch other than master (assuming that the local branch was branched from master). 

The change to do this is in the topic/merge-local-changes branch

**Comment by jimboca** [comment]
I am not convinced that auto-updating nodeservers on restart is a good idea, at least have an option to shut this off per nodeserver or globally?

**Comment by bobpaauwe** [comment]
@jimboca whether or not auto-updating is a good idea is probably a different issue.  I believe I was able to fix this with the right git options so that it doesn't fail.  But it can be disabled.  Adding "devMode": True to the server.json file of the node server will skip the auto-update.  That will give us developers a way to develop without worrying about it overwriting our work.

**Comment by jimboca** [comment]
@bobpaauwe but this issue and auto-updating are related, that's why I mention it.

If it's an option, then it should be an option in the Polyglot config, I know I will forget and commit the change for devMode so having it in the server.json isn't a good place.

**Comment by bpaauwe** [comment]
Yeah @jimboca , not disagreeing with you, I just think you should open a new issue for this so it can be tracked and get the appropriate attention on it.

**Comment by bpaauwe** [comment]
This should not be an issue with release 3.0.15.  

Setting devMode: True in the server.json will prevent PG from trying to update the repository on each start.
The git command has changed so that it should now succeed as long as there aren't conflicts when updating the repository.
