### ISSUE TITLE
Nodeserver state (start/stopped) isn't maintained during Polyglot restart

### ISSUE THREAD

**Issue by bpaauwe** [UniversalDevicesInc/pg3#26]
The current state of a nodeserver, either stopped or running, isn't saved and maintained when Polyglot is restarted.  When Polyglot is restarted, all nodeservers are started.

**Comment by mkohanim** [comment]
This is a very serious bug.

With kind regards,

**********************************
Michel Kohanim
CEO

(p) 818.631.0333
http://www.universal-devices.com
**********************************

________________________________

**Comment by bpaauwe** [comment]
This should be resolved on branch topic/ns-save-state and is available to merge into the next release.

**Comment by Einstein42** [comment]
This isn't a bug, it is a feature requetes. This has been the standard
behavior since PG1

**Comment by jimboca** [comment]
It would be nice to have a disable option, sometimes I just want to leave the NS there but not have it run.  This is mostly a development issue but would be a nice option.

**Comment by bobpaauwe** [comment]
@jimboca how is disabled different from stopped?   The feature (as implemented) leaves the node server stopped until you manually restart it.

**Comment by jimboca** [comment]
To me it's just more clear to specifically disable a nodeserver from auto-start on boot.  Sometimes they are stopped by should be restarted and might be confusing to users, but not a big deal.

**Comment by bpaauwe** [comment]
If you're looking at from the current behavior, then I agree.  If the expectation is that all the node servers will start with Polyglot starts, it will be confusing if some don't.  I've always found the current behavior annoying as my expectations were that if I stopped a node server, it should stay stopped until I want to start it.  It always feels like Polyglot is working against me, like it has control, not me :)

**Comment by bpaauwe** [comment]
Fixed in version 3.0.14
