### ISSUE TITLE
[pg3] error: createNS: SqliteError: table nodeserver has no column named logLevelList

### ISSUE THREAD

**Issue by jimboca** [UniversalDevicesInc/pg3#45]
```
7/25/2021, 19:50:54 [pg3] info: [00:21:b9:02:4a:56_25] :: Creating Nodeserver 'Airscape'
7/25/2021, 19:50:54 [pg3] info: [00:21:b9:02:4a:56_25] :: Cloning repository... /home/admin/dev/pg3/udi-poly-airscape into /var/polyglot/.pg3/ns/00:21:b9:02:4a:56_25
7/25/2021, 19:50:54 [pg3] error: createNS: SqliteError: table nodeserver has no column named logLevelList
    at Database.prepare (<anonymous>)
    at Database.prepare (/var/polyglot/node_modules/better-sqlite3/lib/methods/wrappers.js:5:21)
    at Object.add (/var/polyglot/node_modules/@universaldevices/pg3/lib/models/nodeserver.js:265:6)
    at Object.createNs (/var/polyglot/node_modules/@universaldevices/pg3/lib/services/nodeservers.js:332:14)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

**Comment by bpaauwe** [comment]
Did you have an earlier version of PG3 installed?

The original versions of of the database didn't have the logLevel and the upgrade process doesn't rebuild the database and I think that's what causes this error.

At this point, the easiest solution is to stop PG3, remove the database (/var/polyglot/.pg3/pg3.db) and restart PG3.

**Comment by jimboca** [comment]
Ah yes, that's probably why. I was trying to get it running a while back but never fully succeeded.

**Comment by bpaauwe** [comment]
PG3 should have code to update the database table if needed but I think the expectation was that it would never change.

I figured it was safe enough to make the changes when I did because no one was using PG3 at the time. If any more changes are needed, I think PG3 will have to rebuild the table automatically.

**Comment by jimboca** [comment]
Yes, that fixed the problem.
