### ISSUE TITLE
Pass Polyglot version to node servers

### ISSUE THREAD

**Issue by bpaauwe** [UniversalDevicesInc/pg3#6]
Add a field to the json data set in PG3INIT for the Polyglot version. 

This will allow node servers to tailor their behavior to match the version of Polyglot they are connected to.

**Comment by Einstein42** [comment]
This is done. Passed to STDIN and environment variable PG3INIT as base64 encoded:

    const init = Buffer.from(
      JSON.stringify({
        uuid
        profileNum
        logLevel
        token
        mqttHost
        mqttPort
        secure
        pg3Version
        isyVersion
      })
    ).toString('base64')
