### ISSUE TITLE
Add ability to set node server log level from dashboard

### ISSUE THREAD

**Issue by bpaauwe** [UniversalDevicesInc/pg3#8]
The node server dashboard should provide a control to set the node server log level for each node server. 

The level needs to be available to the interface modules and an API defined that allows the node server to get the currently selected log level.

**Comment by mkohanim** [comment]
+1

With kind regards,

******************************
  Michel Kohanim
  CEO

  (p) 818.631.0333
  http://www.universal-devices.com<http://www.universal-devices.com/>
******************************

**Comment by jimboca** [comment]
The API already exists for the modules in PG2, but I agree there should be a way to also control it from the PG3 UI, and that would probably be preferred method.

**Comment by Goose66** [comment]
+1 - I am thinking about removing this from my nodeservers interface back to the ISY (GV20 driver) and instead implementing it as a custom configuration parameter in PG2.

Why isn't there a "vote up" option in GitHub issues.

**Comment by jimboca** [comment]
I've considered that as well, but would prefer if the custom config would allow me to set a list of choices for the user to select.

**Comment by bpaauwe** [comment]
Implemented in 3.0.15 release
