### ISSUE TITLE
The node server dashboard should provide a control for node discovery

### ISSUE THREAD

**Issue by bpaauwe** [UniversalDevicesInc/pg3#9]
The dashboard should be the one location where node server control is implemented. This means that it should have a control that asks the node server to run its node discovery method.  

This is similar to the existing control to stop a node server.

**Comment by jimboca** [comment]
And should be an optional for those that don't need a discover.

**Comment by Goose66** [comment]
I don't know how I feel about this one. Setting parameters, logging levels, etc. to configure the nodeserver is one thing, but the "Discover Devices" feels more like a "configure devices" think that should be left in ISY Administrative Console, like ZWave and Insteon device "discovery" and configuration.

**Comment by bpaauwe** [comment]
withdrawn
